config/routes.rb
TravelApp::Application.routes.draw do

  resources :users
  match "profile" => "users#profile"
  match "new_profile" => "users#new_profile"
  match "show_profile/:id" => "users#show_profile"
  resources :sessions

  get "log_in" => "sessions#new", :as => "log_in"
  get "log_out" => "sessions#destroy", :as => "log_out"
  
  get "sign_up" => "users#new", :as => "sign_up"   

  root :to => "homes#index"
  get "homes/about"
  match 'homes/contact', :to => 'homes#contact'
   
   

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  
  attr_accessible :user_id, :fname, :lname, :gender, :dob, :country, :state, :city, :address, :pin, :phone, :image, :remote_image_url
  belongs_to :user
  validates :user_id, presence: true
  validates :fname, :lname, :gender, :dob, :country, :state, :city, :address, :pin, :phone, :presence => true
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  
   attr_accessible :email, :password, :password_confirmation
   attr_accessor :password
   before_save :encrypt_password
   
   has_one :profile, dependent: :destroy
   
   validates_confirmation_of :password  
   validates_presence_of :password, :on => :create  
   validates_presence_of :email  
   validates_uniqueness_of :email
   
   def encrypt_password  
     if password.present?  
       self.password_salt = BCrypt::Engine.generate_salt  
       self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)  
     end  
   end
   
   def self.authenticate(email, password)  
     user = find_by_email(email)  
     if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)  
       user  
     else  
      nil  
     end  
   end    
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery
  
    helper_method :current_user       
    private 
    def current_user  
     @current_user ||= User.find(session[:user_id]) if session[:user_id]  
   end  

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
  
  def contact
    if request.post? and params[:contact]
      if contact = Contact.new(params[:contact])
        contact.name = "#{params[:contact][:name]}"
        contact.email = "#{params[:contact][:email]}"
        contact.message = "#{params[:contact][:message]}"
        
        if contact.save
          flash[:notice] = "contact details is saved successfully."
          redirect_to("/")
        else
          render "contact"
        end
        
      end
    end
  end
  
  def about
    
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create  
     user = User.authenticate(params[:email], params[:password])  
     if user  
       session[:user_id] = user.id  
       redirect_to root_url, :notice => "Logged in!"  
     else  
       flash.now.alert = "Invalid email or password"  
       render "new"  
     end  
   end
   
   def destroy  
    session[:user_id] = nil  
    redirect_to root_url, :notice => "Logged out!"  
   end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new  
    @user = User.new  
  end 
  
  def create  
     @user = User.new(params[:user])  
     if @user.save  
       redirect_to root_url, :notice => "Signed up!"  
     else  
       render "new"  
     end  
   end 
   
   def show_profile
    @user = current_user.profile if current_user.present?
   end

   def new_profile
    @profile = Profile.new
   end

   def profile
    user = current_user
    profile = user.build_profile(params[:profile])
    if profile.save
      flash[:notice] = "Profile saved successfully."
      redirect_to "/show_profile/#{current_user.id}"
    else
      flash[:error] = "Something went wrong."
      redirect_to :back
   end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<div id="loading"></div>

<div id="contentContainer">
<div id="content">

<div id="main">
	<div id="handle"></div>
	<div id="closeBox"></div>
	
	<h2 class="entrytitle">About</h2>
	
	<!--BREADCRUMBS-->
	<div id="crumbs"><a href="/">Home</a> &nbsp;/&nbsp; <span class="current">About</span></div>
	
	<!--PAGE CONTENT-->	
	<div class="entry">
		<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consequat libero et libero semper eu elementum odio rutrum. Fusce elementum mi nec urna tristique laoreet. Vestibulum magna massa, volutpat et pellentesque quis, pellentesque tincidunt turpis. Vestibulum vel est arcu, ut eleifend sem. Aliquam lectus mi, commodo id tempus eu, volutpat sit amet massa. Sed ultricies porttitor mauris id vulputate. </p>
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consequat libero et libero semper eu elementum odio rutrum. Fusce elementum mi nec urna tristique laoreet. Vestibulum magna massa, volutpat et pellentesque quis, pellentesque tincidunt turpis. Vestibulum vel est arcu, ut eleifend sem. Aliquam lectus mi, commodo id tempus eu, volutpat sit amet massa. Sed ultricies porttitor mauris id vulputate. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consequat libero et libero semper eu elementum odio rutrum. Fusce elementum mi nec urna tristique laoreet. Vestibulum magna massa, volutpat et pellentesque quis, pellentesque tincidunt turpis. Vestibulum vel est arcu, ut eleifend sem. Aliquam lectus mi, commodo id tempus eu, volutpat sit amet massa. Sed ultricies porttitor mauris id vulputate. </p>								
	</div><!--end entry-->

	<!--COMMENTS (NOT FUNCTIONAL)-->
	<div id="commentToggle" class="toggleButton closed"><span>+</span>2 Comments</div>
    <div class="clear" id="commentsection">
			
		<ol class="commentlist">
			<li class="comment">
				<div class="comment-body">
					<div class="comment-author">
						<img alt='' src='images/avatar.jpg' class='avatar avatar-32 photo'/>		
						<cite class="fn">themolitor</cite> <span class="says">says:</span>		
					</div>
					<div class="commentmetadata">July 7, 2011 at 10:42 pm</div>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consequat libero et libero semper eu elementum odio rutrum. Fusce elementum mi nec urna tristique laoreet. Vestibulum magna massa, volutpat et pellentesque quis, pellentesque tincidunt turpis.</p>
				</div>
			</li>
			<li class="comment">
				<div class="comment-body">
					<div class="comment-author">
						<img alt='' src='images/avatar.jpg' class='avatar avatar-32 photo'/>		
						<cite class="fn">themolitor</cite> <span class="says">says:</span>		
					</div>
					<div class="commentmetadata">July 7, 2011 at 10:42 pm</div>
					<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed consequat libero et libero semper eu elementum odio rutrum. Fusce elementum mi nec urna tristique laoreet. Vestibulum magna massa, volutpat et pellentesque quis, pellentesque tincidunt turpis.</p>
				</div>
			</li>
		</ol><!--end commentlist-->

		<div id="respond">
			<h3>Leave a Reply</h3>
			<form action="#" method="post" id="commentform">
			<p>
				<input type="text" name="author" id="author" value="" size="22" tabindex="1" aria-required='true' />
				<label for="author"><small>Name (required)</small></label>
			</p>
			<p>
				<input type="text" name="email" id="email" value="" size="22" tabindex="2" aria-required='true' />
				<label for="email"><small>Email (required)</small></label>
			</p>
			<p>
				<input type="text" name="url" id="url" value="" size="22" tabindex="3" />
				<label for="url"><small>Website</small></label>
			</p>
			<p><textarea name="comment" id="comment" tabindex="4"></textarea></p>
			<p>
				<input name="submit" type="submit" id="submit" tabindex="5" value="Submit Comment" />
				<input type='hidden' name='comment_post_ID' value='56' id='comment_post_ID' />
				<input type='hidden' name='comment_parent' id='comment_parent' value='0' />
			</p>
			</form>
		</div><!--end respond-->
    </div><!--end commentsection-->
</div><!--end main-->

<script type="text/javascript">
//FULL SCREEN IMAGE BACKGROUND - CHANGE IMAGE URL
jQuery.noConflict(); jQuery(document).ready(function(){jQuery.backstretch("images/thumbs/space.jpg", {speed: 150});});
</script>

<div id="sidebar">
<ul>
<!--WIDGET 1-->
<li class="widget">
	<h2 class="widgettitle">Sponsors</h2>			
	<a href="http://themeforest.net/user/themolitor/portfolio?ref=themolitor">
		<img src="http://www.lakewaparks.com/wp/wp-content/uploads/2011/07/tf_260x120.gif" alt="ThemeForest" />
	</a>
</li><!--end widget-->

<!--WIDGET 2-->
<li class="widget">
	<h2 class="widgettitle">Text Widget</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sagittis aliquet commodo. Sed consequat lorem a quam fermentum auctor. Donec quis nisi mi. In vel justo sem, quis iaculis tellus. Sed molestie imperdiet sapien, sed adipiscing tellus imperdiet at. Donec id orci sed elit eleifend luctus.</p>
</li><!--end widget-->

<!--WIDGET 3-->
<li class="widget">
	<h2 class="widgettitle">Tags</h2>
	<div class="tagcloud">
		<a href='#'>Africa</a>
		<a href='#'>All</a>
		<a href='#'>Argentina</a>
		<a href='#'>Arizona</a>
		<a href='#'>Asia</a>
		<a href='#'>Australia</a>
		<a href='#'>Brazil</a>
		<a href='#'>China</a>
		<a href='#'>Egypt</a>
		<a href='#'>England</a>
		<a href='#'>Europe</a>
		<a href='#'>France</a>
		<a href='#'>India</a>
		<a href='#'>Italy</a>
		<a href='#'>Mexico</a>
		<a href='#'>New York</a>
		<a href='#'>North Africa</a>
		<a href='#'>North America</a>
		<a href='#'>Paris</a>
		<a href='#'>Rome</a>
		<a href='#'>South America</a>
		<a href='#'>UK</a>
		<a href='#'>US</a>
	</div>
</li><!--end widget-->
</ul>
<div class="clear"></div>
</div><!--end sidebar-->

<div class="clear"></div>
</div><!--end content-->
</div><!--end contentContainer-->

app/views/homes/contact.html.erb
<div id="loading"></div>

<div id="contentContainer">
<div id="content">

<div id="main">
	<div id="handle"></div>
	<div id="closeBox"></div>
	
	<h2 class="entrytitle">Contact</h2>
	
	<div id="crumbs"><a href="/">Home</a> &nbsp;/&nbsp; <span class="current">Contact</span></div>	
	<div class="entry">
	
	<!--CONTACT FORM-->
	<%= form_for :contact, :url =>{:action => :contact, :controller => "homes"} do |f| %>
    <p> <%= f.label :name %> </p>
    <p> <%= f.text_field :name%> </p>

    <p> <%= f.label :email %> </p>
    <p> <%= f.email_field :email%> </p>

    <p> <%= f.label :message %> </p>
    <p> <%= f.text_area :message %> </p>

    <p> <%= f.submit %> </p>

    <% end %>
    <!--end contact form-->
    								
	</div><!--end entry-->
		
</div><!--end main-->

<script type="text/javascript">
//FULL SCREEN IMAGE
jQuery.noConflict(); jQuery(document).ready(function(){jQuery.backstretch("images/thumbs/blog.jpg", {speed: 150});});
</script>

<div id="sidebar">
<ul>
<!--WIDGET 1-->
<li class="widget">
	<h2 class="widgettitle">Sponsors</h2>			
	<a href="http://themeforest.net/user/themolitor/portfolio?ref=themolitor">
		<img src="http://www.lakewaparks.com/wp/wp-content/uploads/2011/07/tf_260x120.gif" alt="ThemeForest" />
	</a>
</li><!--end widget-->

<!--WIDGET 2-->
<li class="widget">
	<h2 class="widgettitle">Text Widget</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sagittis aliquet commodo. Sed consequat lorem a quam fermentum auctor. Donec quis nisi mi. In vel justo sem, quis iaculis tellus. Sed molestie imperdiet sapien, sed adipiscing tellus imperdiet at. Donec id orci sed elit eleifend luctus.</p>
</li><!--end widget-->

<!--WIDGET 3-->
<li class="widget">
	<h2 class="widgettitle">Tags</h2>
	<div class="tagcloud">
		<a href='#'>Africa</a>
		<a href='#'>All</a>
		<a href='#'>Argentina</a>
		<a href='#'>Arizona</a>
		<a href='#'>Asia</a>
		<a href='#'>Australia</a>
		<a href='#'>Brazil</a>
		<a href='#'>China</a>
		<a href='#'>Egypt</a>
		<a href='#'>England</a>
		<a href='#'>Europe</a>
		<a href='#'>France</a>
		<a href='#'>India</a>
		<a href='#'>Italy</a>
		<a href='#'>Mexico</a>
		<a href='#'>New York</a>
		<a href='#'>North Africa</a>
		<a href='#'>North America</a>
		<a href='#'>Paris</a>
		<a href='#'>Rome</a>
		<a href='#'>South America</a>
		<a href='#'>UK</a>
		<a href='#'>US</a>
	</div>
</li><!--end widget-->
</ul>
<div class="clear"></div>
</div><!--end sidebar-->

<div class="clear"></div>
</div><!--end content-->
</div><!--end contentContainer-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelApp</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
  
  <!--GOOGLE CUSTOM FONT LINK-->


<%= stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Gruppo', 'style','prettyPhoto','application' %>

<!--SCRIPTS-->

<%= javascript_include_tag 'jquery.min.js','jquery-ui-1.8.13.custom.min.js','prettyphoto.js','activity.js','http://maps.google.com/maps/api/js?sensor=false', 'gmap3.min.js','jquery.backstretch.min.js','jquery.animate-colors-min.js','custom.js',  'https://apis.google.com/js/plusone.js' %>


</head>
<body>
	


<div id="header">
	
	<!--LOGO-->
	<!--<%= link_to "The Navigator" ,'/' %><%= image_tag('images/logo.png',:alt=>"logo") %> -->
	<a id="logo" href="/"><img src="images/logo.png" alt="The Navigator" /></a> 
	<!--DESCRIPTION-->
	<!--NAVIGATION MENU-->
	<div id="navigation">
		<ul id="dropmenu" class="menu">
			<!--CURRENT MENU ITEM (class name = current-menu-item)-->
			
			<% if current_user %>
     			
     			<li> <%= link_to current_user.email, "/show_profile/#{current_user.id}"%> </li>
     		<% end %>
			<li class="current-menu-item"><%= link_to "Home" , '/' %>
				

			<ul class="sub-menu">
				<li><a href="#">Africa</a></li>
				<li><a href="#">Asia</a></li>
				<li><a href="#">Australia</a></li>
				<li><a href="#">Europe</a></li>
				<li><a href="#">North America</a></li>
				<li><a href="#">South America</a></li>
				<li><a href="#">View All</a></li>
			</ul>
			</li>
			
			<li><%= link_to "About", homes_about_path %></li>
			<li><%= link_to "Contact", homes_contact_path %></li>
			
 
			   <% if current_user %>
			   		<!--<li><%= link_to "Edit Profile", :action => "new_profile", :controller => "users" if current_user.present? %></li>-->
     				<li><%= link_to "Log out", log_out_path %></li> 
   				<% else %>  
     				<li><%= link_to "Sign up", sign_up_path %></li>
     				<li><%= link_to "Log in", log_in_path %> </li> 
   				<% end %>  
			
		</ul>
	</div>
</div><!--end header-->
	
  <% flash.each do |name, msg| %>  
     <%= content_tag :div, msg, :id => "flash#{name}" %>  
   <% end %> 

<%= yield %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<div id="footer">

	<!--WIDGET PANEL OPEN/CLOSE-->
	<a href="#" id="widgetsOpen" title="More" class="widgetsToggle">+</a>
	<a href="#" id="widgetsClose" title="Close" class="widgetsToggle">&times;</a>	
	
	<!--SEARCH (NOT FUNCTIONAL)-->	
	<div id="footerSearch">
		<form method="get" action="/">
			<input type="image" src="images/mag_glass.png" id="searchsubmit" alt="GO!" />
			<input type="text" value="" onfocus="this.value=''; this.onfocus=null;"  name="s" id="s" />
		</form>
	</div>
	
	<!--SOCIAL BUTTONS-->
	<div id="socialStuff">
		<a class="socialicon" id="rssIcon" href="#"  title="Subscribe via RSS" rel="nofollow"></a>
		<a class="socialicon" id="facebookIcon" href="#"  title="Facebook" rel="nofollow"></a>
		<a class="socialicon" id="twitterIcon" href="#" title="Follow on Twitter" rel="nofollow"></a>
		<!--
		<a class="socialicon" id="vimeoIcon" href="#" title="Vimeo" rel="nofollow"></a>
		<a class="socialicon" id="skypeIcon" href="#" title="Skype" rel="nofollow"></a>
		<a class="socialicon" id="myspaceIcon" href="#" title="MySpace" rel="nofollow"></a>
		<a class="socialicon" id="flickrIcon" href="#" title="Flickr" rel="nofollow"></a>
		<a class="socialicon" id="linkedinIcon" href="#" title="LinkedIn" rel="nofollow"></a>
		<a class="socialicon" id="youtubeIcon" href="#" title="YouTube" rel="nofollow"></a>
		-->
	</div>
		
	<!--COPYRIGHT NOTICE - IMPORTANT! DO NOT REMOVE GOOGLE NOTICE -->
	<div id="copyright">
	&copy; Wirates.com
	</div>	
	
	<!--THIS SHOULD BE THE TITLE OF THE PAGE-->
	<div class="pageContent">
		<h2>Page Title Here</h2>
	</div>
</div><!--end footer-->



</body>
</html>

app/views/users/new.html.erb
 <div id="loading"></div>

<div id="contentContainer">
<div id="content">

<div id="main">
	<div id="handle"></div>
	<div id="closeBox"></div>
	
	<h2 class="entrytitle">Sign Up</h2>
	
	<div id="crumbs"><a href="/">Home</a> &nbsp;/&nbsp; <span class="current">Sign Up</span></div>	
	<div class="entry">
  	
  	<!--Sign Up FORM-->
   
 <%= form_for @user do |f| %>  
   <% if @user.errors.any? %>  
     <div class="error_messages">  
       <h2>Form is invalid</h2>  
       <ul>  
         <% for message in @user.errors.full_messages %>  
           <li><%= message %></li>  
         <% end %>  
       </ul>  
     </div>  
   <% end %>  
   <p>  
     <%= f.label :email %><br />  
     <%= f.text_field :email %>  
   </p>  
   <p>  
     <%= f.label :password %><br />  
     <%= f.password_field :password %>  
   </p>  
   <p>  
     <%= f.label :password_confirmation %> <br />
     <%= f.password_field :password_confirmation %>  
   </p>  
   <p class="button"><%= f.submit %></p>  
 <% end %>
 
 <!--end Sign Up form-->
 
</div><!--end entry-->
		
</div><!--end main-->

<script type="text/javascript">
//FULL SCREEN IMAGE
jQuery.noConflict(); jQuery(document).ready(function(){jQuery.backstretch("images/thumbs/blog.jpg", {speed: 150});});
</script>

<div id="sidebar">
<ul>
<!--WIDGET 1-->
<li class="widget">
	<h2 class="widgettitle">Sponsors</h2>			
	<a href="http://themeforest.net/user/themolitor/portfolio?ref=themolitor">
		<img src="http://www.lakewaparks.com/wp/wp-content/uploads/2011/07/tf_260x120.gif" alt="ThemeForest" />
	</a>
</li><!--end widget-->

<!--WIDGET 2-->
<li class="widget">
	<h2 class="widgettitle">Text Widget</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sagittis aliquet commodo. Sed consequat lorem a quam fermentum auctor. Donec quis nisi mi. In vel justo sem, quis iaculis tellus. Sed molestie imperdiet sapien, sed adipiscing tellus imperdiet at. Donec id orci sed elit eleifend luctus.</p>
</li><!--end widget-->

<!--WIDGET 3-->
<li class="widget">
	<h2 class="widgettitle">Tags</h2>
	<div class="tagcloud">
		<a href='#'>Africa</a>
		<a href='#'>All</a>
		<a href='#'>Argentina</a>
		<a href='#'>Arizona</a>
		<a href='#'>Asia</a>
		<a href='#'>Australia</a>
		<a href='#'>Brazil</a>
		<a href='#'>China</a>
		<a href='#'>Egypt</a>
		<a href='#'>England</a>
		<a href='#'>Europe</a>
		<a href='#'>France</a>
		<a href='#'>India</a>
		<a href='#'>Italy</a>
		<a href='#'>Mexico</a>
		<a href='#'>New York</a>
		<a href='#'>North Africa</a>
		<a href='#'>North America</a>
		<a href='#'>Paris</a>
		<a href='#'>Rome</a>
		<a href='#'>South America</a>
		<a href='#'>UK</a>
		<a href='#'>US</a>
	</div>
</li><!--end widget-->
</ul>
<div class="clear"></div>
</div><!--end sidebar-->

<div class="clear"></div>
</div><!--end content-->
</div><!--end contentContainer-->

app/views/users/new_profile.html.erb
<div id="loading"></div>

<div id="contentContainer">
<div id="content">

<div id="main">
	<div id="handle"></div>
	<div id="closeBox"></div>
	
	<h2 class="entrytitle">Profile</h2>
	
	<div id="crumbs"><a href="/">Home</a> &nbsp;/&nbsp; <span class="current">Profile</span></div>	
	<div class="entry">
	
	<!--Profile FORM-->



<% if current_user.present? %>
<%= form_for @profile, :url => {:action => "profile", :controller => "users" }, :html => {:multipart => true} do |f| %>

<p>
  <%= f.label :fname, "First Name:"%>
  <%= f.text_field :fname %>
</p>

<p>
  <%= f.label :lname, "Last Name:"%>
  <%= f.text_field :lname %>
</p>

<p>
  <%= f.label :gender, "Gender:"%>
  <%= f.text_field :gender %>
</p>

<p>
  <%= f.label :dob, "Date of Birth:"%>
  <%= f.text_field :dob %>
</p>

<p>
  <%= f.label :country, "Country:"%>
  <%= f.text_field :country %>
</p>

<p>
  <%= f.label :state, "State:"%>
  <%= f.text_field :state %>
</p>

<p>
  <%= f.label :city, "City:"%>
  <%= f.text_field :city %>
</p>

<p>
  <%= f.label :address, "Address:"%>
  <%= f.text_field :address %>
</p>

<p>
  <%= f.label :pin, "Pin Code:"%>
  <%= f.text_field :pin %>
</p>

<p>
  <%= f.label :phone, "Mobile No.:"%>
  <%= f.text_field :phone %>
</p>

<p>
	<%= f.label :image, "Image:"%>
    <%= f.file_field :image %>
</p>
<p>
    <%= f.label :remote_image_url, "or image URL:" %><br />
    <%= f.text_field :remote_image_url %>
</p>

<p><%= f.submit "Save" %>

<% end %>

<% end %>

<!--end Profile form-->
    								
	</div><!--end entry-->
		
</div><!--end main-->

<script type="text/javascript">
//FULL SCREEN IMAGE
jQuery.noConflict(); jQuery(document).ready(function(){jQuery.backstretch("images/thumbs/blog.jpg", {speed: 150});});
</script>

<div id="sidebar">
<ul>
<!--WIDGET 1-->
<li class="widget">
	<h2 class="widgettitle">Sponsors</h2>			
	<a href="http://themeforest.net/user/themolitor/portfolio?ref=themolitor">
		<img src="http://www.lakewaparks.com/wp/wp-content/uploads/2011/07/tf_260x120.gif" alt="ThemeForest" />
	</a>
</li><!--end widget-->

<!--WIDGET 2-->
<li class="widget">
	<h2 class="widgettitle">Text Widget</h2>
	<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer sagittis aliquet commodo. Sed consequat lorem a quam fermentum auctor. Donec quis nisi mi. In vel justo sem, quis iaculis tellus. Sed molestie imperdiet sapien, sed adipiscing tellus imperdiet at. Donec id orci sed elit eleifend luctus.</p>
</li><!--end widget-->

<!--WIDGET 3-->
<li class="widget">
	<h2 class="widgettitle">Tags</h2>
	<div class="tagcloud">
		<a href='#'>Africa</a>
		<a href='#'>All</a>
		<a href='#'>Argentina</a>
		<a href='#'>Arizona</a>
		<a href='#'>Asia</a>
		<a href='#'>Australia</a>
		<a href='#'>Brazil</a>
		<a href='#'>China</a>
		<a href='#'>Egypt</a>
		<a href='#'>England</a>
		<a href='#'>Europe</a>
		<a href='#'>France</a>
		<a href='#'>India</a>
		<a href='#'>Italy</a>
		<a href='#'>Mexico</a>
		<a href='#'>New York</a>
		<a href='#'>North Africa</a>
		<a href='#'>North America</a>
		<a href='#'>Paris</a>
		<a href='#'>Rome</a>
		<a href='#'>South America</a>
		<a href='#'>UK</a>
		<a href='#'>US</a>
	</div>
</li><!--end widget-->
</ul>
<div class="clear"></div>
</div><!--end sidebar-->

<div class="clear"></div>
</div><!--end content-->
</div><!--end contentContainer-->